### ISSUE TITLE
Question: how does this interact with plugins?

### ISSUE THREAD

**Issue by broady** [rafaelmaiolla/remote-vscode#10]
I'm wondering how this interacts with plugins like [`vscode-go`](https://github.com/Microsoft/vscode-go). Does everything work?

I'm not sure how rmate itself works.

**Comment by rafaelmaiolla** [comment]
rmate will just open one file from a remote source.  Colorization may work, but all other features like "Build-on-save" will not work. You will not have the folder loaded in your editor.

**Comment by broady** [comment]
Ah, thought so. Thanks :)
