### ISSUE TITLE
always open file in the same tab now

### ISSUE THREAD

**Issue by happlebao** [rafaelmaiolla/remote-vscode#11]
vscode version: 1.3.1
os: windows 7

how could I open new file in a separate tab?
probably the api changed?

**Comment by rafaelmaiolla** [comment]
That is a new feature for VScode 1.3 - please find the section 'Preview Editors' in  [https://code.visualstudio.com/updates/June_2016#_workbench](https://code.visualstudio.com/updates/June_2016#_workbench) 

You can disable the preview functionality by adding the following to your settings:

```javascript
// Controls if opened editors show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
"workbench.editor.enablePreview": false,
```

**Comment by happlebao** [comment]
wow so fast. Thanks!
