### ISSUE TITLE
Does it work on Windows 10?

### ISSUE THREAD

**Issue by brusMX** [rafaelmaiolla/remote-vscode#13]
I keep getting the Connection refused error.

```
$ rmate file.txt 
connect to localhost port 52698 failed: Connection refused
```

But I'm able to do it if I run the command with Sublime. Am I missing something (and yes the server has been started)?

**Comment by rafaelmaiolla** [comment]
Yes, it works on Windows 10. It is my default environment.

I would check the tunnel and the configured ports, but it is hard to say what could be the issue.

**Comment by rafaelmaiolla** [comment]
Closing issue as there wasn't any new comments.

**Comment by brusMX** [comment]
So it turns out that the port was the problem, during that time you had a different port than the one used in rmate.
