### ISSUE TITLE
Error: command 'extension.startServer' not found

### ISSUE THREAD

**Issue by bmingles** [rafaelmaiolla/remote-vscode#22]
I get the following error message when trying to run `Remote: Start Server`

`Error: command 'extension.startServer' not found`

**Comment by rafaelmaiolla** [comment]
Do you have more details regarding the issue?

I use the extension every day, and I didn't notice any problem.

**Comment by bmingles** [comment]
@rafaelmaiolla I literally just installed today and get that error every time I try the command.

**Comment by rafaelmaiolla** [comment]
ok, I will investigate the issue with a fresh install.

**Comment by rafaelmaiolla** [comment]
There is a new version of the extension, could you please check if it is working?
