### ISSUE TITLE
I don't get the installation guide.

### ISSUE THREAD

**Issue by MattSom** [rafaelmaiolla/remote-vscode#23]
Hey,

Could you help me with the installation part? It makes no sense to me. Where should I add my username and password?
What should
 ```
Go to the remote system and run
rmate -p 52698 file
```
even mean? What is it for?

Thank you!

**Comment by rafaelmaiolla** [comment]
This extension is a "A package that implements the Textmate's 'rmate' feature for VSCode."

So, please check [https://github.com/textmate/rmate](https://github.com/textmate/rmate)
