### ISSUE TITLE
Status bar says "Starting server" and then nothing happens

### ISSUE THREAD

**Issue by julneb** [rafaelmaiolla/remote-vscode#25]
I have tried with several versions of VSCode, most recently Version 1.12.2, running on OSX 10.11.6.

Occasionally it says "Server started" but there is never any ports opened, my configuration is as follows:

    "remote.port": 52689,
    "remote.onstartup": true,
    "remote.host": "127.0.0.1",
 
Also trying to restart from inside the editor only gives the status bar text but no server is ever started/port 52689 remains closed and unbound.

Is there some part of the instructions missing to get this working? I have looked through all output windows and logs I can find without discovering any debug/error info.

**Comment by rafaelmaiolla** [comment]
Extension was updated to version 1.1.0, which includes an small icon in the right side.  So you can check if the server is running.

Could you please re-test to see if the issue is still reproducible?
