### ISSUE TITLE
"Error: Failed to start server" when opening new window

### ISSUE THREAD

**Issue by gristow** [rafaelmaiolla/remote-vscode#27]
Remove-vscode & rmate work perfectly when I just have one VSCode window open. However, if I open a  new window, I get this error message (more of an annoyance, since files will still open in the original window):

![image](https://cloud.githubusercontent.com/assets/8905340/26833370/3dcc121a-4aa0-11e7-8dc8-b7393ea87f4d.png)

**Comment by rafaelmaiolla** [comment]
This is expected if you have set it to automatically start the server on startup.

```javascript
// Launch the server on start up.
"remote.onstartup": true
```

Each window will try to start listening in the same port, so it will fails if the port is already in use.  But note that we can't say if something else is using the port or not.  So, we show the error to warn the user.

**Comment by gristow** [comment]
Got it -- that makes sense as I think about it, given the way VSCode shares very little between window contexts. Thanks!
