### ISSUE TITLE
Can I use Putty for tunneling?

### ISSUE THREAD

**Issue by bromoapp** [rafaelmaiolla/remote-vscode#28]
Hi,

I'm working under Win 10, and totally new to vs code.
I have Ubuntu VM running as a guess os, and I want to edit my app that deployed there.
What I have done:

1. Your plugin installed in my vscode
2. I installed rmate in my Ubuntu
3. I configured my User Settings in my vscode

but I confused with: 

ssh -R 52698:127.0.0.1:52698 user@example.org

Should I install ssh in windows in order to make tunneling command works? I have Putty installed already.
Can I just use Putty tunneling instead? 

Thanks

P.S. Nice work :)

**Comment by rafaelmaiolla** [comment]
Just use Putty tunneling, should be the same.
