### ISSUE TITLE
Error: Failed to start server, port 52698 already in use

### ISSUE THREAD

**Issue by lhrkkk** [rafaelmaiolla/remote-vscode#29]
When configured with    
 "remote.onstartup": true,

Then when open a new window, or restart vscode with multiple windows, the message is given. It seems every window will start a server so it get the message. It should be started only once.

**Comment by rafaelmaiolla** [comment]
Each window is a separate vscode instance, so we can't say when there is one or more open.  If you don't want it to start on every window, set this property to false.

**Comment by lhrkkk** [comment]
Is there any variables refer to the number of windows?  If it exists, we can check it in the start-server function.

**Comment by rafaelmaiolla** [comment]
In the next days, I will add a configuration to don't show the error message for port already in use.

**Comment by rafaelmaiolla** [comment]
New setting added to 1.1.0 version to don't show the error message if set to true
