### ISSUE TITLE
New tabs replacing existing tabs

### ISSUE THREAD

**Issue by ziermmar** [rafaelmaiolla/remote-vscode#36]
Since just recently (starting with VS Code 1.15.0 I think) I'm having issues with remote-vscode. When I open a remote file while already having another file tab open in vscode, the first tab gets replaced by the new file tab. This gets really annoying when you don't think about it and haven't saved in a while. I'm open to suggestions on how to debug this behaviour.

**Comment by rafaelmaiolla** [comment]
Please check you configuration for:

```
// Controls if opened editors show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
"workbench.editor.enablePreview": false,
```

**Comment by ziermmar** [comment]
I think that did it. Thanks!
