### ISSUE TITLE
user@example.org

### ISSUE THREAD

**Issue by JoeWarwick** [rafaelmaiolla/remote-vscode#37]
Funny it is not mentioned. I guess you just need to know.

Create an ssh tunnel
ssh -R 52698:127.0.0.1:52698 user@example.org

user@example.org is not an email address but actually needs to be an external facing Internet address contactable remotely on port 22.

So you will not get this working unless that user@example.org is a dns registered address that forwards port 22 to your development machine through NAT.

This is definitely the hard part and in many cases not possible to do at all. 

I think a warning should be visible on this so poor schlubs don't waste precious time trying to figure out what 'user@example.org' needs to be so this works.

**Comment by DanielFallon** [comment]
@JoeWarwick 

I think the majority of people using this plugin would be familiar with ssh, you can use `-p <port number>` to change the port if necessary
