### ISSUE TITLE
README instruction not clear

### ISSUE THREAD

**Issue by Leedehai** [rafaelmaiolla/remote-vscode#41]
Hi could you please specify in the instructions which steps are performed on the local machine and which are performed on the remote server?

**Comment by gedw99** [comment]
i also had this problem. Could be clearer for sure

**Comment by rafaelmaiolla** [comment]
I will try to update the instructions to add more details.

**Comment by gedw99** [comment]
Thank you.

I am running vagrant and connect using the command "vagrant SSH".

I run gomate inside the guest.

**Comment by gedw99** [comment]
@rafaelmaiolla 

I got it working with vagrant.
Host is OSX
Guest is ubuntu

````

ssh -R 52698:127.0.0.1:52698 -i .vagrant/machines/default/virtualbox/private_key -p 2222 vagrant@127.0.0.1
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-92-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.


Last login: Mon Oct 23 13:40:49 2017 from 10.0.2.2
vagrant@vagrant:~$ gomate /
2017/10/23 13:44:05 VSCode 1

````


Now what though ?
VSCode 1, but what is it. How to see the remote files in my VSCODE folder tree etc ?
Maybe i misunderstand how to use this tool or what it is really for ?

**Comment by rafaelmaiolla** [comment]
This is not used to see all the remote file in VSCode. This extension is used to edit individual files from an ssh session.

As said in the docs, this is a package that implements the Textmate's '[rmate](https://github.com/textmate/rmate)' feature for VSCode.
