### ISSUE TITLE
Opens files in sublime not VS Code

### ISSUE THREAD

**Issue by whyisjacob** [rafaelmaiolla/remote-vscode#44]
So I had the textmate setup for Sublime and after following the directions above, when I type rcode [filemane] it opens the file in sublime over VS code

Is it possible to have both sublime and VS Code as an option or is it one or the other?

Else How would I be able to convert it to open VS Code instead of Sublime Text?

**Comment by rafaelmaiolla** [comment]
You need to use a different port number for VS Code, then both will work.

**Comment by whyisjacob** [comment]
Does the number matter? or will `52699` work?

**Comment by rafaelmaiolla** [comment]
Can be any number, you just need to configure everything with the same number.
VSCode
SSH tunnel
rcode

**Comment by whyisjacob** [comment]
Excellent, thanks! that seemed to work I appreciate your help and assistance on this issue @rafaelmaiolla
