### ISSUE TITLE
Nothing happens when opening a large file

### ISSUE THREAD

**Issue by mafredri** [rafaelmaiolla/remote-vscode#5]
Hi, glad to see there's finally a remote extension for vscode!

I just tried out your extension and ran into this issue while trying to open up a 16MB file from a remote server. The rmate command loads for a while (2.663 s) and then exists (without error) but nothing opens up in vscode. Works fine with smaller files.

**Comment by rafaelmaiolla** [comment]
It seems that there is a bug when the extension is checking the file size before opening it.  I'll fix the issue.

**Comment by rafaelmaiolla** [comment]
The fix checked in will fix the file size issue for text files.  But it seems that there is still a issue for big files.

**Comment by mafredri** [comment]
Thanks for the quick response!

Yeah, I just tried out `0.1.4` and you're right, didn't solve the issue yet.

**Comment by rafaelmaiolla** [comment]
I've made a few changes in de code and the extension is working as expected.  However, VSCode failing to open the big file in the editor. Sill need to investigate that and possibly open a issue for VSCode

**Comment by mafredri** [comment]
I can confirm that files still don't show up in the editor. Interestingly VSCode has no problems opening the file if I scp it to my local computer, but opening it through rmate is definitely not working (although the connection is left open, so the ssh session won't exit).

**Comment by rafaelmaiolla** [comment]
I could confirm that the file was transferred.  But the VSCode API to open the file in the editor is returning null and there isn't any error.

I don't know if you noted, but I changed the extension name to "Remote VSCode".  The old extension "Remote Visual Code Studio" was removed.

**Comment by mafredri** [comment]
> I don't know if you noted, but I changed the extension name to "Remote VSCode".

Ah, I had noted, but did not realize it wouldn't automatically update, thanks.

With the newest version I experience the same behavior as before, except now VSCode actually shows a "failed to open" error (the ssh session is still left active).
