### ISSUE TITLE
Failed to start server, will try again in 10 seconds

### ISSUE THREAD

**Issue by merefield** [rafaelmaiolla/remote-vscode#50]
Hey, thank you for this extremely useful plug-in!

I'm having problems though!  This was working, but then broke on a re-save of the user settings file.

Getting this repeatedly:

"Failed to start server, will try again in 10 seconds}"

In dev console is see this:

```
[Extension Host] [34m[2018-02-21 10:06:31.390] [TRACE] Server - [39mstart true
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.390] [TRACE] Server - [39misOnline
console.ts:123 [Extension Host] [36m[2018-02-21 10:06:31.390] [DEBUG] Server - [39misOnline? false
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.391] [TRACE] StatusBarItem - [39monStarting
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.391] [TRACE] Server - [39mgetPort 52698
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.391] [TRACE] Server - [39mgetHost NaN
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.391] [TRACE] Server - [39monServerError { Error: listen EADDRNOTAVAIL **MY-REMOTE-IP**:52698
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at Server.setupListenHandle [as _listen2] (net.js:1247:19)
	at listenInCluster (net.js:1304:12)
	at doListen (net.js:1428:7)
	at _combinedTickCallback (internal/process/next_tick.js:83:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '**MY-REMOTE-IP**',
  port: 52698 }
console.ts:123 [Extension Host] [34m[2018-02-21 10:06:31.392] [TRACE] StatusBarItem - [39monError
```

Getting this repeated message.  I know its not a machine-wide problem because Atom has a similar plug-in and this is working.

My settings are:

```
{
//-------- Remote VSCode configuration --------

// Port number to use for connection.
"remote.port": 52698,

// Launch the server on start up.
"remote.onstartup": true,

// Address to listen on.
"remote.host": "**MY-REMOTE-IP**",

// If set to true, error for remote.port already in use won't be shown anymore.
"remote.dontShowPortAlreadyInUseError": false,
}
```

btw, I note that equivalent for atom.io, https://atom.io/packages/remote-atom, doesn't require a host IP, thoughts?  I'm not having any issue with the Atom implementation and rmate correctly brings up the remote file.  I'm careful to close Atom before retrying VS Code (and in any case this occurred before I installed remote-atom in my copy of Atom).

**Comment by rafaelmaiolla** [comment]
You don't need to set the "remote.host".
Remove it from your User Settings or set it to 
```
  // Address to listen on.
  "remote.host": "127.0.0.1",
```

**Comment by merefield** [comment]
That fixed it, thank you for your swift response!

**Comment by ruqianl** [comment]
I'm having the same issue, and my remote host is set to 127.0.0.1.
It reporting the same error "Failed to start server, will try again in 10 seconds"

![image](https://user-images.githubusercontent.com/12887308/56101446-1fb90480-5f67-11e9-9000-11512cb95014.png)

![image](https://user-images.githubusercontent.com/12887308/56101487-88a07c80-5f67-11e9-875c-cb395d0da533.png)

**Comment by ruqianl** [comment]
Restarting my machine fixed it.
