### ISSUE TITLE
Enhancement: prevent preview for remotely edited files

### ISSUE THREAD

**Issue by NorthboundTrain** [rafaelmaiolla/remote-vscode#52]
When editing files using this extension, the files are opened as preview editors, meaning they're re-used (this is assuming that preview is turned on via workbench.editor.enablePreview). This occurs even when workbench.editor.enablePreviewFromQuickOpen is set to false (I've no expectation that that setting would affect remote-vscode, but I tried it nonetheless).

It would be nice if this were configurable somehow, either globally for all remote edits, or on a per-file basis via a command-line option. Ideally we could have a global setting and then toggle it via the command-line.

Thanks!

**Comment by rafaelmaiolla** [comment]
The extension doesn't have control over how the file will be open (preview or not).  Maybe you should ask that in VSCode.
