### ISSUE TITLE
The first open tab will get lost if another file is opened

### ISSUE THREAD

**Issue by haichaoyu** [rafaelmaiolla/remote-vscode#54]
Hello,

Thanks to all the contributors for making this project possible. 

I found that when I opened another file, the first opened tab will be overwritten and get lost. Is it a intended feature or to-be-improved one?

Best

**Comment by rafaelmaiolla** [comment]
please check https://github.com/rafaelmaiolla/remote-vscode/issues/36

**Comment by haichaoyu** [comment]
@rafaelmaiolla Thanks!
