### ISSUE TITLE
Rmate doesn't open up files

### ISSUE THREAD

**Issue by enemene123** [rafaelmaiolla/remote-vscode#66]
Setting up the ssh connection in VScode works, but while trying to open a configuration file nothing happens, the command is executed and then I am back on the console again.
There is no error message.

My installation steps:
1. Installed the remote-vscode extension
2. Used the settings 127.0.0.1 with port 52698 for the extension
3. Installed rmate on the remote server
    `sudo wget -O /usr/local/bin/rmate https://raw.githubusercontent.com/aurora/rmate/master/rmate
     sudo chmod a+x /usr/local/bin/rmate`
4. F1 -> Start Server on VScode
5. Terminal: ssh -R 52698:localhost:52698 root@My-Host-IP
6. Trying to open a file: rmate -p 52698 /tmp/tempy.conf
    Or just rmate /tmp/tempy.conf
7. I also tried it with these settings for my ~/.ssh/config
   `Host *
    ForwardAgent yes
    RemoteForward 52698 127.0.0.1:52698`

I checked it again for wrong ports, typos etc. but I can't seem to find the problem.

**Comment by enemene123** [comment]
I got it working after trying some different Versions of rmate.
I think the issue was, that I configured the extension in the GUI settings of VS Code and not in the User Settings. When I tried to configure it in the User Settings, I wasn't able to save the configuration, so there may be some kind of bug with using the GUI for the extensions settings.
Removing and installing it again helped.

**Comment by bajaj689** [comment]
Hi. I am facing exactly the same issue. I tried reinstalling the Remote VS Code extension ,followed the exact sequence of steps as mentioned by @enemene123  above. The issue is that after I run the command- "rmate file.cpp " in Visual Studio Code's terminal, it doesn't open the file in VS Code. Moreover the command returns with no error message. Please help.
